org: cryptofool13
app: sls-library
service: sls-library
frameworkVersion: "3"

custom:
  usersTableName: "users-table-v2-${sls:stage}"
  booksTableName: "books-table-v2-${sls:stage}"

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [BooksTable, Arn]
  environment:
    USERS_TABLE: ${self:custom.usersTableName}
    BOOKS_TABLE: ${self:custom.booksTableName}

functions:
  register-api:
    handler: dist/auth/handler.handler
    events:
      - httpApi: "*"
  library-api:
    handler: dist/books/handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: userName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.usersTableName}
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: isbn
            AttributeType: S
        KeySchema:
          - AttributeName: isbn
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.booksTableName}
